site_name: Scripsi
theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
    accent: teal
  icon:
    logo: material/feather

markdown_extensions:
  - admonition
  - pymdownx.superfences