site_name: Scripsi
site_author: Douglas Reed
site_description: Writing about science, technology and cooking
copyright: Copyright &copy; 2021 Douglas Reed

theme:
  name: material
  custom_dir: custom-theme
  palette:
    scheme: default
    primary: blue grey
    accent: teal
  icon:
    logo: material/feather
  features:
    - navigation.tabs
    - toc.integrate

markdown_extensions:
  - admonition
  - attr_list
  - smarty
  - meta
  - pymdownx.superfences
  - pymdownx.smartsymbols

plugins:
    - search
    - img2fig
    - section-index
