site_name: Scripsi
site_author: Douglas Reed
site_description: Writing about science, technology and cooking
copyright: Copyright &copy; 2021 Douglas Reed

theme:
  name: material
  custom_dir: custom-theme
  palette:
    scheme: default
    primary: blue grey
    accent: teal
  icon:
    logo: material/feather
  features:
    - navigation.tabs
    - toc.integrate

extra_javascript:
  # - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - smarty
  - meta
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

plugins:
    - search
    - img2fig
    - section-index
